### ISSUE TITLE
"Arri Reveal sRGB" looks different from the april 2023 38dd80 build

### ISSUE THREAD

**Issue by Baalvon** [Joegenco/PixelManager#4]
I used the new overhauled a3e7a7 build in Unreal Engine 5.3.1 and noticed the new built-in Arri Reveal sRGB transform looks different from my custom one that is based on your generous instructions. The image looks brighter and washed off now.

![old](https://github.com/Joegenco/PixelManager/assets/29520608/a8c0b5b4-0569-477e-b875-c6bde102a2fd)
![new](https://github.com/Joegenco/PixelManager/assets/29520608/5ba0806c-1f7f-4555-b208-8d4d1732e82f)

My custom Arri Reveal sRGB is shown below:

  - !<ColorSpace>
    name: ARRI Reveal Gamma 2.2 Rec709 CUSTOM
    family: display
    categories: [Display_Encodings]
    encoding: sdr-spaces
    equalitygroup: ""
    bitdepth: 32f
    description: ARRI Reveal with gamma 2.4 curve for Rec.709 color space.
    isdata: false
    from_scene_reference: !<GroupTransform>
      children:
        - !<ColorSpaceTransform> {src: Linear Rec709/sRGB, dst: ARRI LogC4}
        - !<FileTransform> {src: ARRI_LogC4-to-Gamma24_Rec709-D65_v1-65.cube, interpolation: tetrahedral}
        - !<ColorSpaceTransform> {src: Gamma 2.4 EOTF sRGB, dst: Gamma 2.2 EOTF sRGB}

I notice the new config uses a different Log-to-709 cube file.

**Comment by Joegenco** [comment]
EOTF transofrms dont contain a "colorspace" anymore.

You may use 2.2 EOTF Encoding and 2.4 EOTF Encoding instead.

Arri Reveal that is already in the config is the same with what youre adding as "custom" with the exception that it uses 33x33 lut instead of 65x65

LIne 1346 on config.ocio
```
  - !<ColorSpace> #ARRI Reveal sRGB
    name: ARRI Reveal sRGB
    aliases: []
    family: Imagery
    equalitygroup: ""
    bitdepth: unknown
    description: ARRI Reveal Rec709 with sRGB gamma
    isdata: false
    allocation: uniform
    from_scene_reference: !<GroupTransform>
      children:
        - !<ColorSpaceTransform> {src: Linear CIE-XYZ I-E, dst: ARRI LogC4}
        - !<FileTransform> {src: ARRI_LogC4-to-Gamma24_Rec709-D65_v1-33.cube, interpolation: tetrahedral}
        - !<ColorSpaceTransform> {src: 2.4 EOTF Encoding, dst: 2.2 EOTF Encoding}
```

~~UE's viewport OCIO implementation is a bit whack. It works correctly when rendering out of Movie Render Que, however the viewport still has some UE "tone"mapping going on. Changing the UE's default tone mapper settings while OCIO is active affects the image in the viewport, which shouldnt happen if it was feeding the linear rendering space to OCIO.~~

~~Use these prompts to test for yourself. It needs a solution and this is the closest I could come up with.
r.Tonemapper.Quality 0
r.TonemapperGamma 2.2~~
This seems to be fixed now.

~~As far as I can tell ARRI Reveal sRGB works fine.~~
No it doesnt, I will rewamp how I did the gamma transforms, I will remove the named-transforms completely and use the transforms from the "gamma stuff" section.

Working on it.....
